"""Plugin category interfaces for the Firewallo Plugin Framework."""

from .vpn import (
    VPNPluginInterface,
    VPNServerCreate,
    VPNServerResponse,
    VPNServerUpdate,
    VPNClientCreate,
    VPNClientResponse,
    VPNClientUpdate,
    VPNConfigResponse,
    VPNConnectionStatus,
    VPNStatistics,
)

from .firewall import (
    FirewallPluginInterface,
    FirewallAction,
    FirewallProtocol,
    FirewallChain,
    FirewallRuleCreate,
    FirewallRuleResponse,
    FirewallRuleUpdate,
    FirewallZoneCreate,
    FirewallZoneResponse,
    FirewallZoneUpdate,
    FirewallNATRule,
    FirewallStatistics,
    FirewallBackup,
)

from .monitoring import (
    MonitoringPluginInterface,
    MetricType,
    MetricUnit,
    AlertSeverity,
    AlertStatus,
    MonitoringTargetType,
    MetricCreate,
    MetricResponse,
    MetricQuery,
    MetricSeriesResponse,
    AlertRuleCreate,
    AlertRuleResponse,
    AlertRuleUpdate,
    AlertEvent,
    MonitoringTargetCreate,
    MonitoringTargetResponse,
    MonitoringTargetUpdate,
    DashboardCreate,
    DashboardResponse,
    MonitoringStatistics,
)

from .network import (
    NetworkPluginInterface,
    NetworkProtocol,
    InterfaceType,
    InterfaceStatus,
    DHCPMode,
    DNSRecordType,
    LoadBalancerAlgorithm,
    NetworkInterfaceCreate,
    NetworkInterfaceResponse,
    NetworkInterfaceUpdate,
    DHCPServerCreate,
    DHCPServerResponse,
    DHCPLease,
    DNSZoneCreate,
    DNSZoneResponse,
    DNSRecordCreate,
    DNSRecordResponse,
    RouteCreate,
    RouteResponse,
    LoadBalancerCreate,
    LoadBalancerResponse,
    NetworkStatistics,
)

from .security import (
    SecurityPluginInterface,
    SecurityEventType,
    ThreatLevel,
    CertificateType,
    AuthMethod,
    PolicyAction,
    ScanType,
    CertificateCreate,
    CertificateResponse,
    CertificateUpdate,
    TwoFactorSetup,
    TwoFactorResponse,
    SecurityPolicyCreate,
    SecurityPolicyResponse,
    SecurityPolicyUpdate,
    SecurityEvent,
    IntrusionSignature,
    SecurityScanRequest,
    SecurityScanResult,
    AuditLogEntry,
    SecurityStatistics,
)

__all__ = [
    # VPN plugin interface and models
    "VPNPluginInterface",
    "VPNServerCreate",
    "VPNServerResponse",
    "VPNServerUpdate",
    "VPNClientCreate",
    "VPNClientResponse",
    "VPNClientUpdate",
    "VPNConfigResponse",
    "VPNConnectionStatus",
    "VPNStatistics",

    # Firewall plugin interface and models
    "FirewallPluginInterface",
    "FirewallAction",
    "FirewallProtocol",
    "FirewallChain",
    "FirewallRuleCreate",
    "FirewallRuleResponse",
    "FirewallRuleUpdate",
    "FirewallZoneCreate",
    "FirewallZoneResponse",
    "FirewallZoneUpdate",
    "FirewallNATRule",
    "FirewallStatistics",
    "FirewallBackup",

    # Monitoring plugin interface and models
    "MonitoringPluginInterface",
    "MetricType",
    "MetricUnit",
    "AlertSeverity",
    "AlertStatus",
    "MonitoringTargetType",
    "MetricCreate",
    "MetricResponse",
    "MetricQuery",
    "MetricSeriesResponse",
    "AlertRuleCreate",
    "AlertRuleResponse",
    "AlertRuleUpdate",
    "AlertEvent",
    "MonitoringTargetCreate",
    "MonitoringTargetResponse",
    "MonitoringTargetUpdate",
    "DashboardCreate",
    "DashboardResponse",
    "MonitoringStatistics",

    # Network plugin interface and models
    "NetworkPluginInterface",
    "NetworkProtocol",
    "InterfaceType",
    "InterfaceStatus",
    "DHCPMode",
    "DNSRecordType",
    "LoadBalancerAlgorithm",
    "NetworkInterfaceCreate",
    "NetworkInterfaceResponse",
    "NetworkInterfaceUpdate",
    "DHCPServerCreate",
    "DHCPServerResponse",
    "DHCPLease",
    "DNSZoneCreate",
    "DNSZoneResponse",
    "DNSRecordCreate",
    "DNSRecordResponse",
    "RouteCreate",
    "RouteResponse",
    "LoadBalancerCreate",
    "LoadBalancerResponse",
    "NetworkStatistics",

    # Security plugin interface and models
    "SecurityPluginInterface",
    "SecurityEventType",
    "ThreatLevel",
    "CertificateType",
    "AuthMethod",
    "PolicyAction",
    "ScanType",
    "CertificateCreate",
    "CertificateResponse",
    "CertificateUpdate",
    "TwoFactorSetup",
    "TwoFactorResponse",
    "SecurityPolicyCreate",
    "SecurityPolicyResponse",
    "SecurityPolicyUpdate",
    "SecurityEvent",
    "IntrusionSignature",
    "SecurityScanRequest",
    "SecurityScanResult",
    "AuditLogEntry",
    "SecurityStatistics",
]
